### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by jbk1988** [goedh452/homebridge-harmony-tv#1]
Hi, I followed all your instructions, but I can't get the Harmony API part to work properly. 

It is displaying in HomeKit, but obviously won't connect.

Here's what I'm getting:

[12/23/2019, 7:52:35 PM] TypeError: Cannot read property 'slug' of undefined
    at HarmonyTV.setPowerState (/usr/lib/node_modules/homebridge-harmony-tv/index.js:282:51)
    at Characteristic.Active.emit (events.js:210:5)
    at Characteristic.Active.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:210:5)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:210:5)

Dec 23 17:28:55 homebridge systemd[1]: harmony-api-server.service: Main process exited, code=exited, status=1/FAILURE
Dec 23 17:28:55 homebridge systemd[1]: harmony-api-server.service: Unit entered failed state.
Dec 23 17:28:55 homebridge systemd[1]: harmony-api-server.service: Failed with result 'exit-code'.
Dec 23 17:29:05 homebridge systemd[1]: harmony-api-server.service: Service hold-off time over, scheduling restart.
Dec 23 17:29:05 homebridge systemd[1]: Stopped A simple server allowing you to query/control multiple local Harmony Home Hubs over HTTP or MQTT.
Dec 23 17:29:05 homebridge systemd[1]: Started A simple server allowing you to query/control multiple local Harmony Home Hubs over HTTP or MQTT.
Dec 23 17:29:06 homebridge harmony-api[1011]: warn:    --minUptime not set. Defaulting to: 1000ms
Dec 23 17:29:06 homebridge harmony-api[1011]: warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Dec 23 17:29:06 homebridge harmony-api[1011]: error: Could not read .foreverignore file.
Dec 23 17:29:06 homebridge harmony-api[1011]: error: ENOENT: no such file or directory, open '/var/lib/harmony-api/.foreverignore'
Dec 23 17:29:33 homebridge harmony-api[1011]: Starting discovery.
Dec 23 17:29:33 homebridge harmony-api[1011]: Hub discovered: XXX
Dec 23 17:29:33 homebridge harmony-api[1011]: Hub discovered: XXX
Dec 23 17:29:33 homebridge harmony-api[1011]: Hub discovered: XXX
Dec 23 17:29:33 homebridge harmony-api[1011]: Updating activities for XXX.
Dec 23 17:29:33 homebridge harmony-api[1011]: Updating state for XXX.
Dec 23 17:29:33 homebridge harmony-api[1011]: Updating devices for XXX.
Dec 23 17:29:33 homebridge harmony-api[1011]: events.js:187
Dec 23 17:29:33 homebridge harmony-api[1011]:       throw er; // Unhandled 'error' event
Dec 23 17:29:33 homebridge harmony-api[1011]:       ^
Dec 23 17:29:33 homebridge harmony-api[1011]: Error: ENOSPC: System limit for number of file watchers reached, watch '/var/lib/harmony-api/FFmpeg/libavcodec/vc1data.h'
Dec 23 17:29:33 homebridge harmony-api[1011]:     at FSWatcher.start (internal/fs/watchers.js:165:26)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at Object.watch (fs.js:1329:11)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at createFsWatchInstance (/usr/lib/node_modules/forever/node_modules/chokidar/lib/nodefs-handler.js:37:15)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at setFsWatchListener (/usr/lib/node_modules/forever/node_modules/chokidar/lib/nodefs-handler.js:80:15)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/forever/node_modules/chokidar/lib/nodefs-handler.js:228:14)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at FSWatcher.NodeFsHandler._handleFile (/usr/lib/node_modules/forever/node_modules/chokidar/lib/nodefs-handler.js:255:21)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at FSWatcher.<anonymous> (/usr/lib/node_modules/forever/node_modules/chokidar/lib/nodefs-handler.js:473:21)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at FSReqCallback.oncomplete (fs.js:159:5)
Dec 23 17:29:33 homebridge harmony-api[1011]: Emitted 'error' event on FSWatcher instance at:
Dec 23 17:29:33 homebridge harmony-api[1011]:     at FSWatcher._handleError (/usr/lib/node_modules/forever/node_modules/chokidar/index.js:257:10)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at createFsWatchInstance (/usr/lib/node_modules/forever/node_modules/chokidar/lib/nodefs-handler.js:39:5)
Dec 23 17:29:33 homebridge harmony-api[1011]:     at setFsWatchListener (/usr/lib/node_modules/forever/node_modules/chokidar/lib/nodefs-handler.js:80:15)
Dec 23 17:29:33 homebridge harmony-api[1011]:     [... lines matching original stack trace ...]
Dec 23 17:29:33 homebridge harmony-api[1011]:     at FSReqCallback.oncomplete (fs.js:159:5) {
Dec 23 17:29:33 homebridge harmony-api[1011]:   errno: -28,
Dec 23 17:29:33 homebridge harmony-api[1011]:   syscall: 'watch',
Dec 23 17:29:33 homebridge harmony-api[1011]:   code: 'ENOSPC',
Dec 23 17:29:33 homebridge harmony-api[1011]:   path: '/var/lib/harmony-api/FFmpeg/libavcodec/vc1data.h',
Dec 23 17:29:33 homebridge harmony-api[1011]:   filename: '/var/lib/harmony-api/FFmpeg/libavcodec/vc1data.h'
Dec 23 17:29:33 homebridge harmony-api[1011]: }
Dec 23 17:29:33 homebridge systemd[1]: harmony-api-server.service: Main process exited, code=exited, status=1/FAILURE
Dec 23 17:29:33 homebridge systemd[1]: harmony-api-server.service: Unit entered failed state.
Dec 23 17:29:33 homebridge systemd[1]: harmony-api-server.service: Failed with result 'exit-code'.
Dec 23 17:29:44 homebridge systemd[1]: harmony-api-server.service: Service hold-off time over, scheduling restart.

**Comment by goedh452** [comment]
Hi!
It's very difficult for me to give support on the Harmony API since it isn't my software, but it seams that forever isn't installed on your pi. More information about Harmony API can be found https://github.com/maddox/harmony-api.
